#!/usr/bin/env python3
"""Regenerate Tables S3-S5 with the AUMC calcium and prothrombin rows corrected (2026-09-22, 063).

The archived AUMC feature-construction code multiplies two prepared fields by 10
(00.data_aumc/feature_data/generate_aumcdb_icu_feature.ipynb, cell 1: ``df.pt=df.pt*10`` and
``df.calcium=df.calcium*10``). After division by 10 the AUMC values match MIMIC-IV ionized
calcium (median about 1.13 mmol/L) and MIMIC-IV/eICU-CRD INR (median about 1.3), whereas the
MIMIC-IV and eICU-CRD ``calcium`` field is total calcium in mg/dL (median about 8.2). AUMC has
no INR field and no total-calcium field in this matrix.

For the descriptive tables only, this version therefore reports AUMC ``calcium`` / 10 as ionized
calcium (mmol/L) and AUMC ``pt`` / 10 as INR (leaving the AUMC prothrombin-time row empty, as in
eICU-CRD). All other rules come unchanged from ``regenerate_supplementary_tables.py``, which is not
modified; outputs are written to a new directory so the previous snapshot is preserved.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import regenerate_supplementary_tables as base  # noqa: E402


def parse_args() -> argparse.Namespace:
    repo = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source-matrix",
        type=Path,
        default=(
            repo
            / "00_frozen_inputs/data_snapshot/remote_project_snapshot"
            / "04.other_feature_in_three_dataset/00.data_merge/df_saki_timeseries_feature_all.csv"
        ),
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=repo / "02_revision_outputs/tables/harmonized_longitudinal_tables_20260922_aumc_ca_inr",
    )
    return parser.parse_args()


def harmonize(source: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    selected, audit = base.harmonize(source)
    aumc = selected.dataset == "aumcdb"
    if selected.loc[aumc, "inr"].notna().any():
        raise ValueError("AUMC INR is unexpectedly populated")
    before = selected.loc[aumc, ["calcium", "pt", "inr"]].describe().T
    pt = pd.to_numeric(selected.loc[aumc, "pt"], errors="coerce")
    calcium = pd.to_numeric(selected.loc[aumc, "calcium"], errors="coerce")
    selected.loc[aumc, "inr"] = pt / 10
    selected.loc[aumc, "pt"] = np.nan
    selected.loc[aumc, "calcium"] = calcium / 10
    after = selected.loc[aumc, ["calcium", "pt", "inr"]].describe().T
    check = before.add_prefix("before_").join(after.add_prefix("after_"))
    return selected, audit, check


def build_tables(source: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, pd.DataFrame]]:
    long, tables = base.build_tables(source)
    relabel = (long.cohort == "AUMC") & (long.feature == "calcium")
    long.loc[relabel, "display_name"] = "Ionized calcium"
    long.loc[relabel, "unit"] = "mmol/L"
    table = tables["AUMC"]
    table.index = pd.MultiIndex.from_tuples(
        [("Ionized calcium", "mmol/L") if key == ("Calcium", "mg/dL") else key for key in table.index],
        names=table.index.names,
    )
    return long, tables


def write_report(out_dir: Path, audit: pd.DataFrame, check: pd.DataFrame) -> None:
    rows = []
    for feature in base.FEATURES:
        transform = base.TRANSFORM[feature]
        if feature == "calcium":
            transform += "; AUMC: ionized calcium (mmol/L), archived value divided by 10"
        elif feature == "inr":
            transform = "AUMC: archived prothrombin field divided by 10 (INR); unavailable where absent"
        elif feature == "pt":
            transform += "; AUMC field reported as INR instead"
        rows.append({"source_variable": feature, "display_name": base.DISPLAY[feature],
                     "common_unit": base.UNITS[feature], "revision_transform_or_summary": transform})
    pd.DataFrame(rows).to_csv(out_dir / "longitudinal_variable_dictionary.csv", index=False)
    check.round(4).to_csv(out_dir / "aumc_calcium_inr_check.csv")
    focus = audit.loc[audit.feature.isin(["fio2", "bilirubin", "hematocrit"])]
    text = f"""# Regenerated longitudinal supplementary tables (AUMC calcium and INR corrected)

Generated by `01_revision_analysis/07_tables_figures/regenerate_supplementary_tables_20260922_aumc_ca_inr.py`
from the same audited source matrix and with the same rules as
`regenerate_supplementary_tables.py` (unchanged; previous outputs remain in
`harmonized_longitudinal_tables/`), plus one additional AUMC rule.

## Additional AUMC rule

The archived AUMC feature-construction code multiplies the prepared `calcium` and `pt`
fields by 10. After division by 10 they correspond to ionized calcium (mmol/L) and INR.
Table S4 therefore reports `calcium` / 10 as ionized calcium and `pt` / 10 as INR; the AUMC
prothrombin-time row is empty, as in eICU-CRD. MIMIC-IV and eICU-CRD are unchanged.

{check.round(4).to_markdown()}

## Prespecified harmonization (unchanged)

- eICU FiO2 was converted from fraction to percent and values outside 21-100% were set
  to missing for these descriptive tables.
- AUMC bilirubin was converted from micromol/L to mg/dL by division by 17.1.
- Hematocrit fractions (0.05-0.80) were converted to percent; plausible percentage
  values (5-80) were retained; other values were set to missing.
- Urine output is the arithmetic mean of six-hour window totals, not a daily sum.

{focus.round(4).to_markdown(index=False)}
"""
    (out_dir / "REGENERATED_TABLES_README.md").write_text(text, encoding="utf-8")


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=False)
    source = pd.read_csv(args.source_matrix)
    if source.duplicated(["dataset", "stay_id", "time"]).any():
        raise ValueError("Source matrix contains duplicate cohort-patient-time rows")
    harmonized, audit, check = harmonize(source)
    long, tables = build_tables(harmonized)
    long.to_csv(args.out_dir / "harmonized_longitudinal_long.csv", index=False)
    audit.to_csv(args.out_dir / "harmonization_missingness_audit.csv", index=False)
    for cohort, table in tables.items():
        table.to_csv(args.out_dir / f"Table_S{ {'MIMIC-IV': 3, 'AUMC': 4, 'eICU-CRD': 5}[cohort] }_{cohort}.csv")
    write_report(args.out_dir, audit, check)
    print(args.out_dir)


if __name__ == "__main__":
    main()
